@startuml packages_online_shopping_entities
set namespaceSeparator none
package "online_shopping.domain.entities" as online_shopping.domain.entities {
}
package "online_shopping.domain.entities.account" as online_shopping.domain.entities.account {
}
package "online_shopping.domain.entities.admin" as online_shopping.domain.entities.admin {
}
package "online_shopping.domain.entities.cart_item" as online_shopping.domain.entities.cart_item {
}
package "online_shopping.domain.entities.catalog" as online_shopping.domain.entities.catalog {
}
package "online_shopping.domain.entities.credit_card" as online_shopping.domain.entities.credit_card {
}
package "online_shopping.domain.entities.customer" as online_shopping.domain.entities.customer {
}
package "online_shopping.domain.entities.electronic_bank_transfer" as online_shopping.domain.entities.electronic_bank_transfer {
}
package "online_shopping.domain.entities.guest" as online_shopping.domain.entities.guest {
}
package "online_shopping.domain.entities.notification" as online_shopping.domain.entities.notification {
}
package "online_shopping.domain.entities.order" as online_shopping.domain.entities.order {
}
package "online_shopping.domain.entities.order_item" as online_shopping.domain.entities.order_item {
}
package "online_shopping.domain.entities.order_log" as online_shopping.domain.entities.order_log {
}
package "online_shopping.domain.entities.payment" as online_shopping.domain.entities.payment {
}
package "online_shopping.domain.entities.payment_method" as online_shopping.domain.entities.payment_method {
}
package "online_shopping.domain.entities.payment_transaction" as online_shopping.domain.entities.payment_transaction {
}
package "online_shopping.domain.entities.product" as online_shopping.domain.entities.product {
}
package "online_shopping.domain.entities.product_category" as online_shopping.domain.entities.product_category {
}
package "online_shopping.domain.entities.product_image" as online_shopping.domain.entities.product_image {
}
package "online_shopping.domain.entities.product_review" as online_shopping.domain.entities.product_review {
}
package "online_shopping.domain.entities.product_variant" as online_shopping.domain.entities.product_variant {
}
package "online_shopping.domain.entities.shipment" as online_shopping.domain.entities.shipment {
}
package "online_shopping.domain.entities.shipment_log" as online_shopping.domain.entities.shipment_log {
}
package "online_shopping.domain.entities.shopping_cart" as online_shopping.domain.entities.shopping_cart {
}
online_shopping.domain.entities --> online_shopping.domain.entities.account
online_shopping.domain.entities --> online_shopping.domain.entities.admin
online_shopping.domain.entities --> online_shopping.domain.entities.cart_item
online_shopping.domain.entities --> online_shopping.domain.entities.catalog
online_shopping.domain.entities --> online_shopping.domain.entities.credit_card
online_shopping.domain.entities --> online_shopping.domain.entities.customer
online_shopping.domain.entities --> online_shopping.domain.entities.electronic_bank_transfer
online_shopping.domain.entities --> online_shopping.domain.entities.guest
online_shopping.domain.entities --> online_shopping.domain.entities.notification
online_shopping.domain.entities --> online_shopping.domain.entities.order
online_shopping.domain.entities --> online_shopping.domain.entities.order_item
online_shopping.domain.entities --> online_shopping.domain.entities.order_log
online_shopping.domain.entities --> online_shopping.domain.entities.payment
online_shopping.domain.entities --> online_shopping.domain.entities.payment_method
online_shopping.domain.entities --> online_shopping.domain.entities.payment_transaction
online_shopping.domain.entities --> online_shopping.domain.entities.product
online_shopping.domain.entities --> online_shopping.domain.entities.product_category
online_shopping.domain.entities --> online_shopping.domain.entities.product_image
online_shopping.domain.entities --> online_shopping.domain.entities.product_review
online_shopping.domain.entities --> online_shopping.domain.entities.product_variant
online_shopping.domain.entities --> online_shopping.domain.entities.shipment
online_shopping.domain.entities --> online_shopping.domain.entities.shipment_log
online_shopping.domain.entities --> online_shopping.domain.entities.shopping_cart
online_shopping.domain.entities.admin --> online_shopping.domain.entities.account
online_shopping.domain.entities.cart_item --> online_shopping.domain.entities.product
online_shopping.domain.entities.cart_item --> online_shopping.domain.entities.product_variant
online_shopping.domain.entities.catalog --> online_shopping.domain.entities.product
online_shopping.domain.entities.customer --> online_shopping.domain.entities.account
online_shopping.domain.entities.customer --> online_shopping.domain.entities.product_review
online_shopping.domain.entities.customer --> online_shopping.domain.entities.shopping_cart
online_shopping.domain.entities.product --> online_shopping.domain.entities.product_category
online_shopping.domain.entities.product --> online_shopping.domain.entities.product_image
online_shopping.domain.entities.product --> online_shopping.domain.entities.product_variant
online_shopping.domain.entities.product_review --> online_shopping.domain.entities.product
online_shopping.domain.entities.shopping_cart --> online_shopping.domain.entities.cart_item
online_shopping.domain.entities.account ..> online_shopping.domain.entities.credit_card
online_shopping.domain.entities.account ..> online_shopping.domain.entities.electronic_bank_transfer
online_shopping.domain.entities.admin ..> online_shopping.domain.entities.product
online_shopping.domain.entities.admin ..> online_shopping.domain.entities.product_category
online_shopping.domain.entities.customer ..> online_shopping.domain.entities.order
online_shopping.domain.entities.customer ..> online_shopping.domain.entities.product
online_shopping.domain.entities.guest ..> online_shopping.domain.entities.account
online_shopping.domain.entities.order ..> online_shopping.domain.entities.order_item
online_shopping.domain.entities.order ..> online_shopping.domain.entities.order_log
online_shopping.domain.entities.order ..> online_shopping.domain.entities.payment
online_shopping.domain.entities.order ..> online_shopping.domain.entities.shipment
online_shopping.domain.entities.order_log ..> online_shopping.domain.entities.notification
online_shopping.domain.entities.payment ..> online_shopping.domain.entities.payment_method
online_shopping.domain.entities.payment ..> online_shopping.domain.entities.payment_transaction
online_shopping.domain.entities.payment_method ..> online_shopping.domain.entities.credit_card
online_shopping.domain.entities.payment_method ..> online_shopping.domain.entities.electronic_bank_transfer
online_shopping.domain.entities.shipment ..> online_shopping.domain.entities.shipment_log
online_shopping.domain.entities.shipment_log ..> online_shopping.domain.entities.notification
@enduml
